/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exam2p;

import giovynet.serial.Baud;
import giovynet.serial.Com;
import giovynet.serial.Parameters;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MMort
 */
public class Datos extends javax.swing.JFrame {

    /**
     * Creates new form GUI_COMUNICADOR
     */
      DefaultTableModel datos = new DefaultTableModel();
    
    
    Com puertors232;
    Parameters config;
    String cad_recibe = "";
    String dat;
  InputStream aux;
    DataInputStream flujo;
    DataOutputStream flujoset;
    String recibirEther = "";
    boolean estado_red=false;
    static int PUERTO;       
    String recibir = "";
    
    ServerSocket Servidor;
    Socket Cliente;
    OutputStream set;
    
    public Datos() {
        initComponents();
         model();
    }
            
    public void model() {       
        String[] cabecera ={"ID","Nombre", "Correo","Estado"};
        datos.setColumnIdentifiers(cabecera);
        tabla.setModel(datos);
    }
    public void Limpiar(){
        int filas = datos.getRowCount();
        
        for(int i = 0; i < filas; i++){
            datos.removeRow(0);
            Datos_Recibidos_Ethernet.setText("");
        }
    }
    
 public abstract class Recibir_Ethernet extends Thread {  
        @Override
        public void run (){
           
            try {
                Servidor = new ServerSocket(PUERTO);          
                while(true){
                    Cliente=Servidor.accept();         
                    flujo = new DataInputStream(Cliente.getInputStream());   
                    recibirEther = flujo.readUTF();         
                    Datos_Recibidos_Ethernet.append("Dato CLIENTE: "+recibirEther+"\n");     
                    if(recibirEther.equals("0")){
                        recibir="Apagado";
                    }
                   if(recibirEther.equals("1")){
                        recibir="Encendido";
                    }
                    
    
                    
                    puertors232.sendString(recibirEther);
                    datos.addRow(new Object[]{" ",recibir});     
                }
            } catch (IOException ex) {
                Logger.getLogger(Datos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Datos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
     
     Conectar Bsed = new Conectar();
    Connection Base = Bsed.conectar();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnConfiguracion = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        COMPUERTAS = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Campo_borrar = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Datos_Recibidos_Ethernet = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 500));

        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 380, 140));

        jLabel3.setText("Puerto COM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel4.setText("Puerto Ethernet");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 130, 30));

        btnConfiguracion.setText("Configuracion");
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 130, 30));

        btnActivar.setText("Activar Red");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, 30));

        btnGrabar.setText("Grabar BD");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 110, 30));

        btnConsultar.setText("Consultar BD");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 110, 30));

        COMPUERTAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COM1", "COM2", "COM3", "COM4" }));
        COMPUERTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMPUERTASActionPerformed(evt);
            }
        });
        getContentPane().add(COMPUERTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 130, 30));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 20, -1));
        getContentPane().add(Campo_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 70, 30));

        btnBorrar.setText("Borrar en BD");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 110, 30));

        Datos_Recibidos_Ethernet.setColumns(20);
        Datos_Recibidos_Ethernet.setRows(5);
        jScrollPane3.setViewportView(Datos_Recibidos_Ethernet);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, 110));

        jLabel6.setText("Datos Ethernet");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel7.setText("Nombre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        try {
            // TODO add your handling code here:
            config = new Parameters();
            config.setPort(COMPUERTAS.getSelectedItem().toString());     
            config.setBaudRate(Baud._9600);
            config.setMinDelayWrite(10);
            puertors232 = new Com (config);
            JOptionPane.showMessageDialog(null,"Puerto"+COMPUERTAS+": disponible");
            

        } catch (Exception ex) {
            Logger.getLogger(Datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed

        PUERTO = Integer.parseInt(txtID.getText());
        JOptionPane.showMessageDialog(null, "Conectado");
        Recibir_Ethernet red = new Recibir_Ethernet (){};
        red.start();
        
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
      try {
            PreparedStatement PS = Base.prepareStatement("INSERT INTO personas(ID,Nombre, Correo, Estado) VALUES (?,?,?,?)");
            PS.setString(1,null);
            PS.setString(2,txtName.getText());
            PS.setString(3,txtEmail.getText());
            PS.setString(4,recibir);         
            PS.executeUpdate();
            Consultar();
        } catch (SQLException ex) {
            Logger.getLogger(Datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Consultar();
    }//GEN-LAST:event_btnConsultarActionPerformed
    
    public void Consultar(){
        Limpiar();
        String[] datosBD = new String[4];
        String SQL = "SELECT * FROM personas";
        try {
            Statement Ba = Base.createStatement();
            ResultSet consulta = Ba.executeQuery(SQL);
            while(consulta.next()){
                datosBD[0]=consulta.getString(1);
                datosBD[1]=consulta.getString(2);
                datosBD[2]=consulta.getString(3);
                datosBD[3]=consulta.getString(4);
                datos.addRow(datosBD);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        String borrar = "DELETE FROM personas WHERE Id="+Campo_borrar.getText();

        try {
            Statement  Borrar = Base.createStatement();
            Borrar.execute(borrar);
            Consultar();
        } catch (SQLException ex) {
            Logger.getLogger(Datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void COMPUERTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMPUERTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMPUERTASActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> COMPUERTAS;
    private javax.swing.JTextField Campo_borrar;
    private javax.swing.JTextArea Datos_Recibidos_Ethernet;
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
